import Image from 'next/image'
import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '../styles/index.scss'

import { ReduxProvider } from '@/store/provider'

import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <ReduxProvider>
      <body>
         <Navbar />

        {children}

        <Footer />
      </body>
      </ReduxProvider>
    </html>
  )
}

