import Image from 'next/image'
import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '../styles/index.scss'

const logo_image = require('../assets/logo_svg.svg')
const user_image = require('../assets/user_svg.svg')
const add_image = require('../assets/add_svg.svg')

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <div className="navbar">
          <Link href={'/'}>
          <div className="logo">
            <Image
              src={JSON.parse(JSON.stringify(logo_image))}
              alt="Logo image"
            />
            <p className="logo-name hidden-media">GrogList</p>
          </div></Link>
          <nav className="nav">
            <div className="nav-item">
              <Link  href={'/list/add'}>
                <Image
                  className='svg-img'
                  src={JSON.parse(JSON.stringify(add_image))}
                  alt="User image"
                />
                <p className='hidden-media'>Create list</p>
              </Link>
            </div>
            <div className="nav-item user-item">
              <Link href={'/account'}>
                <Image
                  className='svg-img'
                  src={JSON.parse(JSON.stringify(user_image))}
                  alt="User image"
                />
              </Link>
            </div>
          </nav>
        </div>

        {children}

        <footer className='footer navbar'>
          <div className="footer-links">
            <Link href={'/login'}>
            <div className="nav-item">
              Login
            </div>
            </Link>
            <Link href={'/register'}>
            <div className="nav-item">
              Sign up
            </div>
            </Link>
          </div>
          <p className="trademark">All right reserved GrocList@2024</p>
        </footer> 
      </body>
    </html>
  )
}
